name: 'Baidu Tieba Auto Sign'

on:
    push:
    schedule:
   # 定时任务，在每天的5点推送天气信息到邮箱
     - cron: '0 21 * * *'



jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: 'Install dependencies'
        run: python -m pip install -r requirements.txt
      - name: 'Start Sign'
        run: python  main_lz_c1.py
      - name: 'save'
        run: |
          git config --global user.email 1031346629@qq.com
          git config --global user.name sym
          git add *
          git commit -m "update"
          git push -u origin master
